### PR TITLE
Fix #49 Add SQL server and database create, delete and update operations 

### LINKED ISSUE #49: Support for Azure SQL Service
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

This allows nodecloud to extend its first support to SQL service of Azure Cloud Provider. :1st_place_medal: 
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by raju249**
## What did you implement:

Closes #49 

## How did you implement it:
Added azure-rest sdk for authentication to azure service.
Added azure-arm-sql nodejs sdk for doing operations on azure cloud.

## How can we verify it:
Run azure example inside `examples/database/azure-sql.js`

## Todos:

- [x] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Comment by rehrumesh** [comment]
On hold as this will overlap GSoC project. Temporarly closing.

**Comment by raju249** [comment]
Sure @rehrumesh 
I thought we could add :sweat_smile:

**Comment by rehrumesh** [comment]
We could when the time comes @raju249. Sorry that I had to close this at the moment. Hope you understand the reason. Why don't you leverage your AWS knowledge to improve the nodecloud aws provider? We need your hand there.

**Comment by raju249** [comment]
Yes, on it now :smile:

**Pull request closed without merging**
